apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: object-classifier
resources:
  - object-classifier-data-pvc.yaml
  - object-classifier-data-extract-job.yaml
  - strimzi-nodepools.yaml
  - strimzi-kafka.yaml
  - kafka-topics.yaml
  - object-classifier-consumer.yaml
  - object-classifier-producer.yaml
