apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-classifier-images
  namespace: object-classifier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
