{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "object-classifier.namespace" . }}
  labels:
    {{- include "object-classifier.labels" . | nindent 4 }}
{{- end }}
